// Generated by scripts/build-test-wasm.mjs — do not edit by hand.

/** (module */
export const scorer = 'AGFzbQEAAAABBwFgAn9/AX4DAgEABQMBAAIHEwIGbWVtb3J5AgAGdmVyaWZ5AAAKOQE3AgF/AX5BACECQgAhAwJAA0AgAiABTw0BIANCH34gACACai0AAK18IQMgAkEBaiECDAALCyADCw=='

/** (module */
export const endless = 'AGFzbQEAAAABBwFgAn9/AX4DAgEABQMBAAEHEwIGbWVtb3J5AgAGdmVyaWZ5AAAKCwEJAANADAALQgAL'

/** (module */
export const importer = 'AGFzbQEAAAABCwJgAAF+YAJ/fwF+AgsBA2VudgNub3cAAAMCAQEFAwEAAQcTAgZtZW1vcnkCAAZ2ZXJpZnkAAQoGAQQAEAAL'

/** (module */
export const private_ = 'AGFzbQEAAAABBwFgAn9/AX4DAgEABQMBAAEHCgEGdmVyaWZ5AAAKBgEEAEIBCw=='

/** (module */
export const refuses = 'AGFzbQEAAAABBwFgAn9/AX4DAgEABQMBAAEHEwIGbWVtb3J5AgAGdmVyaWZ5AAAKBQEDAAAL'

export const bytes = (base64: string) =>
  Uint8Array.from(atob(base64), (ch) => ch.charCodeAt(0))
